project_id = "peubkwmtvjmaajlvtlul"

[functions]
  [functions.ai-insights]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.classify-cost]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
