import type { ModeCopy } from './types';

export const businessCopy: ModeCopy = {
  glossary: {
    inflow: 'Receita',
    inflowSingular: 'receita',
    outflow: 'Custos',
    outflowSingular: 'custo',
    result: 'Lucro',
    resultDay: 'Lucro do dia',
    margin: 'Margem',
    addInflow: 'Registrar receita',
    addOutflow: 'Registrar custo',
    aiPersona: 'consultor financeiro para microempreendedores brasileiros',
  },
  alerts: {
    costsRisingTitle: 'Custos em alta',
    costsRisingMsg: 'Seu custo aumentou nos últimos 3 dias. Sua margem pode cair.',
    costsRisingHint: 'Revise seus custos variáveis',
    resultDroppingTitle: 'Lucro em queda',
    resultDroppingMsg: 'Seu lucro caiu 3 dias seguidos. Se continuar assim, pode ter prejuízo.',
    lossProjectionTitle: 'Previsão de prejuízo',
    lossProjectionMsg: (loss) => `Se continuar assim, você terminará a semana com prejuízo de ${loss}.`,
    lossProjectionHint: 'Aumente as receitas ou reduza custos',
    growthTitle: 'Lucro crescendo',
    growthMsg: (proj) => `Se manter esse ritmo, seu lucro semanal pode chegar a ${proj}.`,
    lowMarginTitle: 'Margem muito baixa',
    lowMarginMsg: (pct) => `Sua margem está em ${pct}%. Ideal é acima de 20%.`,
    lowMarginHint: 'Revise seus preços ou custos',
    topCostHint: 'Negocie com fornecedores',
    goalReachedTitle: 'Meta atingida!',
    goalReachedMsg: (target) => `Você já atingiu sua meta de lucro mensal de ${target}!`,
    goalAtRiskTitle: 'Meta em risco',
    goalAtRiskMsg: (p, e) => `Você atingiu ${p}% da meta, mas deveria estar em ${e}%.`,
    goalAtRiskHint: 'Intensifique as receitas',
    bestDayTitle: (day) => `Melhor dia: ${day}`,
    bestDayMsg: (avg, day) => `Lucro médio de ${avg} às ${day}s. Foque mais receita nesse dia.`,
  },
  inflowCategories: ['Venda', 'Serviço', 'PIX recebido', 'Encomenda', 'Outros'],
  outflowCategoriesVariable: ['Mercadoria', 'Insumos', 'Estoque', 'Embalagens'],
  outflowCategoriesFixed: ['Aluguel', 'Energia', 'Internet', 'Salários', 'Software'],
};
