import type { ModeCopy } from './types';

export const personalCopy: ModeCopy = {
  glossary: {
    inflow: 'Entradas',
    inflowSingular: 'entrada',
    outflow: 'Gastos',
    outflowSingular: 'gasto',
    result: 'Quanto sobrou',
    resultDay: 'Sobrou hoje',
    margin: 'Economia',
    addInflow: 'Adicionar entrada',
    addOutflow: 'Adicionar gasto',
    aiPersona: 'organizador financeiro pessoal para brasileiros',
  },
  alerts: {
    costsRisingTitle: 'Gastos em alta',
    costsRisingMsg: 'Seus gastos subiram nos últimos 3 dias. Está sobrando menos.',
    costsRisingHint: 'Revise gastos do dia a dia',
    resultDroppingTitle: 'Sobrando menos',
    resultDroppingMsg: 'Está sobrando menos a cada dia. Se continuar, pode ficar no vermelho.',
    lossProjectionTitle: 'Risco de ficar no vermelho',
    lossProjectionMsg: (loss) => `Se continuar assim, vai terminar a semana com ${loss} a menos do que entrou.`,
    lossProjectionHint: 'Reduza gastos não essenciais',
    growthTitle: 'Sobrando bem',
    growthMsg: (proj) => `Mantendo esse ritmo, deve sobrar ${proj} esta semana.`,
    lowMarginTitle: 'Sobrando pouco',
    lowMarginMsg: (pct) => `Está sobrando só ${pct}% do que entra. O ideal é guardar pelo menos 20%.`,
    lowMarginHint: 'Corte gastos variáveis',
    topCostHint: 'Veja se dá pra reduzir',
    goalReachedTitle: 'Meta atingida!',
    goalReachedMsg: (target) => `Você já guardou sua meta mensal de ${target}!`,
    goalAtRiskTitle: 'Meta em risco',
    goalAtRiskMsg: (p, e) => `Você guardou ${p}% da meta, mas deveria estar em ${e}%.`,
    goalAtRiskHint: 'Reveja seus gastos',
    bestDayTitle: (day) => `Melhor dia: ${day}`,
    bestDayMsg: (avg, day) => `Em média sobrou ${avg} às ${day}s.`,
  },
  inflowCategories: ['Salário', 'Freelancer', 'PIX recebido', 'Renda extra', 'Venda', 'Outros'],
  outflowCategoriesVariable: ['Alimentação', 'Transporte', 'Lazer', 'Compras', 'Saúde'],
  outflowCategoriesFixed: ['Aluguel', 'Contas', 'Assinaturas', 'Educação'],
};
