import type { ModeCopy } from './types';

export const personalCopy: ModeCopy = {
  glossary: {
    inflow: 'Entradas',
    inflowSingular: 'entrada',
    outflow: 'Gastos',
    outflowSingular: 'gasto',
    result: 'Quanto sobrou',
    resultDay: 'Sobrou hoje',
    margin: 'Economia',
    addInflow: 'Adicionar entrada',
    addOutflow: 'Adicionar gasto',
    aiPersona: 'organizador financeiro pessoal para brasileiros',
    contextLabel: 'Finanças pessoais',
    marginLabel: 'Economia',
    marginLongLabel: 'Percentual economizado',
    performanceTitle: 'Evolução',
    performanceSubtitle: 'Acompanhe sua vida financeira',
    revenueOfLabel: 'entradas',
    profitRealLabel: 'Saldo real',
    profitPerDay: 'Sobra/dia',
    costPerDay: 'Gasto/dia',
    weekSummaryLabel: 'Resumo da semana',
    weeklySummaryProfit: 'Sobrou',
    costsPageTitle: 'Mapa de gastos',
    costsPageSubtitle: 'Entenda para onde seu dinheiro está indo',
    costOperationalLabel: 'Gasto por período',
    costRealLabel: 'Gasto real',
    costOperationalDesc: 'Quanto você gasta por dia em média',
    costRealDesc: 'Quanto você gasta no mês todo',
    costAlertTitle: 'Gastos acima do ideal',
    costRankingTitle: 'Ranking de gastos',
    noCostsLabel: 'Nenhum gasto registrado',
    costFeedback: 'Gasto registrado',
    costModalButton: 'Registrar gasto',
    costModalTitle: 'Registrar gasto',
    costModalSubtitle: 'Descreva o gasto e informe a categoria',
    costPlaceholder: 'Ex: mercado, conta de luz, aluguel...',
    categoryPlaceholder: 'Ex: Alimentação, Moradia, Lazer...',
    variableLabel: 'Variável',
    variableHint: 'Alimentação, lazer, compras',
    fixedLabel: 'Fixo',
    fixedHint: 'Aluguel, contas, assinaturas',
    goalLabel: 'Meta de economia',
    goalProfitLabel: 'Economia',
    goalMarginLabel: 'Economia %',
    navCosts: 'Gastos',
    navPerformance: 'Evolução',
  },
  alerts: {
    costsRisingTitle: 'Gastos em alta',
    costsRisingMsg: 'Seus gastos subiram nos últimos 3 dias. Está sobrando menos.',
    costsRisingHint: 'Revise gastos do dia a dia',
    resultDroppingTitle: 'Sobrando menos',
    resultDroppingMsg: 'Está sobrando menos a cada dia. Se continuar, pode ficar no vermelho.',
    lossProjectionTitle: 'Risco de ficar no vermelho',
    lossProjectionMsg: (loss) => `Se continuar assim, vai terminar a semana com ${loss} a menos do que entrou.`,
    lossProjectionHint: 'Reduza gastos não essenciais',
    growthTitle: 'Sobrando bem',
    growthMsg: (proj) => `Mantendo esse ritmo, deve sobrar ${proj} esta semana.`,
    lowMarginTitle: 'Sobrando pouco',
    lowMarginMsg: (pct) => `Está sobrando só ${pct}% do que entra. O ideal é guardar pelo menos 20%.`,
    lowMarginHint: 'Corte gastos variáveis',
    topCostHint: 'Veja se dá pra reduzir',
    goalReachedTitle: 'Meta atingida!',
    goalReachedMsg: (target) => `Você já guardou sua meta mensal de ${target}!`,
    goalAtRiskTitle: 'Meta em risco',
    goalAtRiskMsg: (p, e) => `Você guardou ${p}% da meta, mas deveria estar em ${e}%.`,
    goalAtRiskHint: 'Reveja seus gastos',
    bestDayTitle: (day) => `Melhor dia: ${day}`,
    bestDayMsg: (avg, day) => `Em média sobrou ${avg} às ${day}s.`,
  },
  inflowCategories: ['Salário', 'Freelancer', 'PIX recebido', 'Renda extra', 'Venda', 'Outros'],
  outflowCategoriesVariable: ['Alimentação', 'Transporte', 'Lazer', 'Compras', 'Saúde'],
  outflowCategoriesFixed: ['Aluguel', 'Contas', 'Assinaturas', 'Educação'],
};
