// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-entries.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_entries_default = defineTool({
  name: "list_entries",
  title: "List revenue entries",
  description: "List the signed-in user's revenue (income) entries, optionally filtered by date range.",
  inputSchema: {
    from: z.string().optional().describe("Start date YYYY-MM-DD (inclusive)."),
    to: z.string().optional().describe("End date YYYY-MM-DD (inclusive)."),
    limit: z.number().int().min(1).max(500).optional().describe("Max rows (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser(ctx).from("entries").select("id,date,amount,category,description,source").eq("user_id", ctx.getUserId()).order("date", { ascending: false }).limit(limit ?? 100);
    if (from) q = q.gte("date", from);
    if (to) q = q.lte("date", to);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-entry.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_entry_default = defineTool2({
  name: "create_entry",
  title: "Create revenue entry",
  description: "Insert a revenue (income) entry for the signed-in user.",
  inputSchema: {
    amount: z2.number().describe("Amount in the user's currency."),
    date: z2.string().describe("Date YYYY-MM-DD."),
    category: z2.string().optional(),
    description: z2.string().optional(),
    source: z2.string().optional().describe("Origin: manual, auto, estimated.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async ({ amount, date, category, description, source }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser2(ctx).from("entries").insert({ user_id: ctx.getUserId(), amount, date, category, description, source: source ?? "manual" }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/list-costs.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_costs_default = defineTool3({
  name: "list_costs",
  title: "List costs",
  description: "List the signed-in user's costs, optionally filtered by date range or classification (fixed/variable).",
  inputSchema: {
    from: z3.string().optional().describe("Start date YYYY-MM-DD (inclusive)."),
    to: z3.string().optional().describe("End date YYYY-MM-DD (inclusive)."),
    classification: z3.enum(["fixed", "variable"]).optional(),
    limit: z3.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, classification, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser3(ctx).from("costs").select("id,date,amount,category,subcategory,classification,type,description,spread_days").eq("user_id", ctx.getUserId()).order("date", { ascending: false }).limit(limit ?? 100);
    if (from) q = q.gte("date", from);
    if (to) q = q.lte("date", to);
    if (classification) q = q.eq("classification", classification);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { costs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-cost.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_cost_default = defineTool4({
  name: "create_cost",
  title: "Create cost",
  description: "Insert a cost (expense) for the signed-in user.",
  inputSchema: {
    amount: z4.number(),
    date: z4.string().describe("Date YYYY-MM-DD."),
    classification: z4.enum(["fixed", "variable"]).describe("Fixed spreads over spread_days; variable is a one-off."),
    category: z4.string().optional(),
    subcategory: z4.string().optional(),
    description: z4.string().optional(),
    type: z4.string().optional(),
    spread_days: z4.number().int().min(1).max(365).optional().describe("For fixed costs, number of days to spread (default 30).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async ({ amount, date, classification, category, subcategory, description, type, spread_days }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser4(ctx).from("costs").insert({
      user_id: ctx.getUserId(),
      amount,
      date,
      classification,
      category,
      subcategory,
      description,
      type: type ?? classification,
      spread_days: spread_days ?? (classification === "fixed" ? 30 : 1)
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { cost: data }
    };
  }
});

// src/lib/mcp/tools/get-summary.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function monthRange(month) {
  const now = /* @__PURE__ */ new Date();
  const [y, m] = month ? month.split("-").map(Number) : [now.getFullYear(), now.getMonth() + 1];
  const from = `${y}-${String(m).padStart(2, "0")}-01`;
  const last = new Date(y, m, 0).getDate();
  const to = `${y}-${String(m).padStart(2, "0")}-${String(last).padStart(2, "0")}`;
  return { from, to };
}
var get_summary_default = defineTool5({
  name: "get_summary",
  title: "Get financial summary",
  description: "Return revenue, costs, profit and margin for the given month (defaults to current month).",
  inputSchema: {
    month: z5.string().optional().describe("Month as YYYY-MM. Defaults to current month.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ month }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { from, to } = monthRange(month);
    const sb = supabaseForUser5(ctx);
    const uid = ctx.getUserId();
    const [entriesRes, costsRes] = await Promise.all([
      sb.from("entries").select("amount").eq("user_id", uid).gte("date", from).lte("date", to),
      sb.from("costs").select("amount").eq("user_id", uid).gte("date", from).lte("date", to)
    ]);
    if (entriesRes.error) return { content: [{ type: "text", text: entriesRes.error.message }], isError: true };
    if (costsRes.error) return { content: [{ type: "text", text: costsRes.error.message }], isError: true };
    const revenue = (entriesRes.data ?? []).reduce((s, r) => s + Number(r.amount ?? 0), 0);
    const costs = (costsRes.data ?? []).reduce((s, r) => s + Number(r.amount ?? 0), 0);
    const profit = revenue - costs;
    const margin = revenue > 0 ? profit / revenue * 100 : 0;
    const summary = { period: { from, to }, revenue, costs, profit, margin };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "peubkwmtvjmaajlvtlul";
var mcp_default = defineMcp({
  name: "lucro-real-mcp",
  title: "Lucro Real",
  version: "0.1.0",
  instructions: "Tools for Lucro Real, a financial tracker. Use `get_summary` for monthly revenue/costs/profit/margin. Use `list_entries` / `list_costs` to read movements and `create_entry` / `create_cost` to add them for the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_entries_default, create_entry_default, list_costs_default, create_cost_default, get_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
